class Math2Exception(Exception):
    pass
